### ISSUE TITLE
Sticky

### ISSUE THREAD

**Issue by pieterbeulque** [mrhenry/custom-elements-helpers#14]
Tough problems :man_shrugging: 

[Inspiration](http://leafo.net/sticky-kit/)

**Comment by yvesvanbroekhoven** [comment]
This can be closed as we are moving forward with the CSS spec:
https://developer.mozilla.org/en-US/docs/Web/CSS/position#Sticky_positioning

**Comment by pieterbeulque** [comment]
Yes, that'll cover most cases. Thank you.
