### ISSUE TITLE
The boolean attribute getter is too naive

### ISSUE THREAD

**Issue by romainmenke** [mrhenry/custom-elements-helpers#26]
https://github.com/mrhenry/custom-elements-helpers/blob/ed62b1a373dee9d64da493b8f97aae97390a8f2b/src/internal/attribute-methods-generator.js#L28

`<my-component my-bool-attr="false"></my-component>`

This will have the attribute getter return "true".

**Comment by pieterbeulque** [comment]
You are confusing [what a boolean attribute is in the HTML specification](http://w3c.github.io/html/infrastructure.html#sec-boolean-attributes) with enumerated attributes (e.g. [`contenteditable`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/contenteditable)).

> The presence of a boolean attribute on an element represents the true value, and the absence of the attribute represents the false value.

This means that `my-bool-attr`, `my-bool-attr=""` and `my-bool-attr="my-bool-attr"` are the _valid_ ways of setting the boolean attribute to true. `my-bool-attr="false"` is invalid HTML but will resolve to true as the spec says. You can see this behavior with another, default boolean attribute like `hidden`.

```js
const div = document.createElement('div');
div.hidden; // false
div.setAttribute('hidden', 'false');
div.hidden; // true
```
